### ISSUE TITLE
Alizer executable called go.exe !!!!

### ISSUE THREAD

**Issue by jeffmaury** [redhat-developer/alizer#104]
Maybe because the Go module ends with go ?

**Comment by lstocchi** [comment]
Just tried on my machine and it works fine apparently. How do you build the executable? 
If you run `go build -o alizer.exe` does it get changed to `go.exe`?

**Comment by jeffmaury** [comment]
I tried `go build ./...` (as Makefile) but does not seem to work on Windows so I tried `go build`

**Comment by lstocchi** [comment]
Ah ok. Yes if i execute `go build` on linux it's the same, but not sure what i can do here. Do i fix the makefile to execute the build command with an output name? Because there is nothing i can do in the code.

**Comment by jeffmaury** [comment]
If there is a command in the Makefile that works on all platforms, that should be good then
