### ISSUE TITLE
Create test repository for alizer

### ISSUE THREAD

**Issue by lstocchi** [redhat-developer/alizer#107]
We should create an extra repo to include all projects to be used when testing alizer

**Comment by jeffmaury** [comment]
Or have a test infra based on https://github.com/go-git/go-git

**Comment by lstocchi** [comment]
So you want to download repos directly using that api? Wouldn't it be more prone to not-predictable errors? Let's say we write a test that uses the repo X to verify that alizer is able to find port 80, it succeed. After months the maintainers of that repo update it and changes the port... our test would fail.

**Comment by jeffmaury** [comment]
> So you want to download repos directly using that api? Wouldn't it be more prone to not-predictable errors? Let's say we write a test that uses the repo X to verify that alizer is able to find port 80, it succeed. After months the maintainers of that repo update it and changes the port... our test would fail.

Unless your refer a specific commit or tag

**Comment by lstocchi** [comment]
could we use any repo no matter which policy it has in this way? As we only download it and then delete everything or we are still subject to that?

**Comment by jeffmaury** [comment]
> could we use any repo no matter which policy it has in this way? As we only download it and then delete everything or we are still subject to that?

I think we need to respect the license
