### ISSUE TITLE
devfile selection: dotNet version is detected correctly

### ISSUE THREAD

**Issue by kadel** [redhat-developer/alizer#135]
Using application from https://github.com/redhat-developer/s2i-dotnetcore-persistent-ex/tree/dotnet-6.0/app

when calling `recognizer.DetectComponentsInRoot`, it correctly detects that app is using .NET 6:0

```
# Running recognizer.DetectComponentsInRoot("./s2i-dotnetcore-persistent-ex/app")
  Name: app Path: /Users/tkral/Code/odo-examples/s2i-dotnetcore-persistent-ex/app/
    {Name:C# Aliases:[csharp dotnet .NET] Weight:100 Frameworks:[net6.0] Tools:[] CanBeComponent:true}
    {Name:Smalltalk Aliases:[squeak] Weight:100 Frameworks:[] Tools:[] CanBeComponent:false}
```

but `recognizer.SelectDevFileFromTypes`  matches only dotnet50 Devfile, but there is better suited dotnet60 devfile in the registry

```
# Runing recognizer.SelectDevFileFromTypes("./s2i-dotnetcore-persistent-ex/app")
  {Name:dotnet50 Language:.NET ProjectType:dotnet Tags:[.NET]}
```

**Comment by lstocchi** [comment]
@kadel The best way for me would be to have a tag that defines the version. The only tag i see in the registry for all .net devfiles is `.NET`. It would be good to have `.net5.0`, `.net6.0` or `.net7.0` based on the specific devfile. In that case alizer should work. The only way i have now to pick the right devfile is using the name which doesn't seem to me a solid idea.

**Comment by kadel** [comment]
OK, that makes sense. I'll open PR to update tags for .net stacks.

**Comment by thepetk** [comment]
I've opened an issue here: https://github.com/devfile/api/issues/1087 to be able to track this better.

**Comment by thepetk** [comment]
Update:
**Target date** for this issue 26 Apr 2023.

I've created a [PR](https://github.com/redhat-developer/alizer/pull/193) for this case. It adds 3 unit tests for devfile detection in order to ensure that if we update the tags of the devfiles, alizer should work fine

**Comment by thepetk** [comment]
I've created a [PR](https://github.com/devfile/registry/pull/181) in the devfile registry repo in order to update the stack tags and match our requirements.

**Comment by thepetk** [comment]
The [registry PR](https://github.com/devfile/registry/pull/181) is now merged. After the merge of https://github.com/redhat-developer/alizer/pull/193 this issue will be fixed.
