### ISSUE TITLE
Alizer should support devfile tag as Spring Boot

### ISSUE THREAD

**Issue by yangcao77** [redhat-developer/alizer#136]
devfile stack & samples are looking to update the spring boot project with more appropriate tags. https://github.com/redhat-developer/alizer/blob/8f7afff3b7cde384ca6ae640a6917d4a8060431b/go/pkg/apis/recognizer/devfile_recognizer.go#L152-L153

However, Alizer expect the devfile tag to match exactly what's been detected as the framework, and that's why changing devfile tag from `Spring` to `Spring Boot` would cause problem and Alizer would failed the detection and return the project devfile using Quarkus one. 
https://github.com/redhat-developer/alizer/blob/8f7afff3b7cde384ca6ae640a6917d4a8060431b/go/pkg/apis/recognizer/devfile_recognizer.go#L152-L153

Alizer need to support `Spring Boot` devfile tag in this case. 

**Update @thepetk :**
Target date: 10 Apr 2023

**Comment by thepetk** [comment]
**Update**: I've created a [PR](https://github.com/redhat-developer/alizer/pull/169) in order to recognize tag `Spring Boot` too for `Spring boot` framework.
