### ISSUE TITLE
WildFly and EAP framework detection

### ISSUE THREAD

**Issue by jfdenise** [redhat-developer/alizer#148]
WildFly framework detection rules:
* A maven project.
* The presence in the pom.xml file of a Maven plugin with groupId=="org.wildfly.plugins", artifactId=="wildfly-maven-plugin"

JBoss EAP framework detection rules:
* A maven project.
* The presence in the pom.xml file of a Maven plugin with groupId=="org.jboss.eap.plugins", artifactId=="eap-maven-plugin"

Update from @thepetk:
target date: 18 Apr 2023

**Comment by elsony** [comment]
This item should cover:
1. custom language and framework detection to recognize the Wildfly and JBoss EAP application type
2. properly match the Wildfly and Jboss stacks using Alizer when one exists in a devfile registry

**Comment by thepetk** [comment]
> "custom language and framework detection to recognize the Wildfly and JBoss EAP application type"

Looking at the current project structure I would say that the WildFly/JBoss frameworks could be added to the Java frameworks (Detected by the Java detector). Does the "custom" means that we want to check if the wildfly/jboss frameworks exist, no matter what is the language of the project?

**Comment by thepetk** [comment]
Update: I've created a [PR](https://github.com/redhat-developer/alizer/pull/161) and I'm able to recognize `wildfly` and `Jboss EAP`. I'm still working on the port recognition.

**Comment by thepetk** [comment]
Update: A new approach for `Wildfly` and `JBoss EAP` is needed. More detailed, a workaround for more specific framework recognition (check `artifactId` not only `groupId`) is necessary for this feature.
