### ISSUE TITLE
Add descriptions in public functions and improve code comments

### ISSUE THREAD

**Issue by thepetk** [redhat-developer/alizer#154]
## Which area this feature is related to?

/area cli
/area library

# Issue details

All functions that can be used by other projects or other modules inside Alizer, should have a description describing what is the function doing, what is using etc.

Additionally, the comments inside the code should be improved and aligned to the devfile project

**Target date:** 16 May 2023

**Comment by mike-hoang** [comment]
Created pr (https://github.com/redhat-developer/alizer/pull/203) which is ready for review. Updating the target date to accommodate the review process
