### ISSUE TITLE
Migrate to gosec

### ISSUE THREAD

**Issue by michael-valdron** [redhat-developer/alizer#160]
## Which area this feature is related to?

/area ci

## Issue details

Currently, alizer uses Snyk to check for vulnerabilities in the dependencies. Migrating to use gosec and dependabot will ensure dependencies are regularly updated as well as ensuring good security in the current go source code. This also keeps it consistent with how devfile source repositories are checked.

[UPDATE] @thepetk 

This issue will be focusing on gosec and we have created a separate issue for dependabot ( #180 )

## Related Issues

redhat-developer/alizer#119

**Comment by thepetk** [comment]
Update: I've opened a [PR](https://github.com/redhat-developer/alizer/pull/179) for the gosec intergration (I'm adding it to the already existing `build-go` workflow).

For the dependabot part, I have created a separate issue [alizer#180](https://github.com/redhat-developer/alizer/issues/180). As this repo is about to be onboarded to another org I would say we can migrate to dependabot after the onboarding when it will be easier to do it (no need to create a new bot for dependabot etc).

**Comment by michael-valdron** [comment]
> Update: I've opened a [PR](https://github.com/redhat-developer/alizer/pull/179) for the gosec intergration (I'm adding it to the already existing `build-go` workflow).
> 
> For the dependabot part, I have created a separate issue [alizer#180](https://github.com/redhat-developer/alizer/issues/180). As this repo is about to be onboarded to another org I would say we can migrate to dependabot after the onboarding when it will be easier to do it (no need to create a new bot for dependabot etc).
> 
> @michael-valdron if you have no objection, we could update the content of this issue to focus on gosec too, so we can track better the progress.

Yeah I agree, we can change the focus of this issue to just gosec and use #180 to track the migration to dependabot.

**Comment by thepetk** [comment]
Nice :) I've updated the issue title and description!
