### ISSUE TITLE
Create issue templates

### ISSUE THREAD

**Issue by michael-valdron** [redhat-developer/alizer#162]
## Which area this feature is related to?

/area documentation

## Issue details

Having starting templates for new issues would improve efficiency and clarity in creating these issues. The templates should consist of what can be seen under [devfile/api](https://github.com/devfile/api/issues/new/choose).

## Related Issues

UPDATE: @thepetk 
**Target Date**: 23 May 2023

**Comment by thepetk** [comment]
I've created a [PR](https://github.com/redhat-developer/alizer/pull/205) for this issue. I've also implemented the same logic, in order to test my solution [here](https://github.com/thepetk/gpg_card_reset/issues/templates/edit)

**Comment by thepetk** [comment]
UPDATE: All review comments have been resolved, waiting for final review
