### ISSUE TITLE
Remove Java and JS builds and intergration tests from workflow

### ISSUE THREAD

**Issue by thepetk** [redhat-developer/alizer#173]
## Which area this feature is related to?

/area test-automation

## Issue details

We need to have more clear workflows without any tests and builds for the two deprecated implementations - `Javascript` and `Java`.

**Target date:** 16 May 2023

**Comment by mike-hoang** [comment]
pr https://github.com/redhat-developer/alizer/pull/192 will close issues #172 and #173
