### ISSUE TITLE
Flatten structure of the Project after the removal of JS and Java

### ISSUE THREAD

**Issue by thepetk** [redhat-developer/alizer#177]
## Which area this feature is related to?

/kind enhancement

## Issue details

After the removal of the two deprecated implementations (JS and Java), it would be nice if we move all content from `go/` folder into `root`.

Things to note:
1. There is a duplicate resource folder (`go/utils/langfiles/resources/*` - identical to - `resources/*`) where we have the same language files. The only instance using the `go/utils/langfiles/resources` is the `.github/workflows/checkLang.yaml`. We need to remove those files and update the workflow to use the `resources/` ones.
2. This update will have an impact to all open PRs. So we need to coordinate before merging.

**Target date:** June 30

**Comment by mike-hoang** [comment]
Created new alizer here: https://github.com/devfile/alizer

This PR must be completed first before any contribution and usage for the new repo
