### ISSUE TITLE
Update go version

### ISSUE THREAD

**Issue by michael-valdron** [redhat-developer/alizer#182]
## Which area this feature is related to?

/area releng

## Issue details

The go version which alizer uses (go 1.17) is long since deprecated. To keep up with security patches and up to date dependency packages, an update to later versions of go is needed. In addition, this will also require dependency packages to be updated to match compatibility with the go version targeted.

## Related Issues

UPDATE: @thepetk 
**Target date**: 28 Apr 2023

**Comment by thepetk** [comment]
Update: I'm investigating the snyk failure job failure before merging.
