### ISSUE TITLE
Javascript devfile is selected for PHP project

### ISSUE THREAD

**Issue by thepetk** [redhat-developer/alizer#188]
Which area this feature is related to?

/area library

## Issue details

I've tried to analyze and select devfile for a [Lavarel project](https://github.com/devfile-samples/devfile-stack-php-laravel.git). Alizer is able to analyze PHP as language:
```json
[
	{
		"Name": "PHP",
		"Aliases": [
			"inc"
		],
		"Weight": 94,
		"Frameworks": [],
		"Tools": [],
		"CanBeComponent": false
	},
	{
		"Name": "Hack",
		"Aliases": null,
		"Weight": 94,
		"Frameworks": [],
		"Tools": [],
		"CanBeComponent": false
	},
	{
		"Name": "JavaScript",
		"Aliases": [
			"js",
			"node",
			"nodejs",
			"TypeScript"
		],
		"Weight": 5,
		"Frameworks": [],
		"Tools": [
			"NodeJs",
			"Node.js"
		],
		"CanBeComponent": true
	}
]
```
But because it only detects one component (Javascript) when I tried to get the devfile I had:
```json
[
	{
		"Name": "nodejs",
		"Language": "JavaScript",
		"ProjectType": "Node.js",
		"Tags": [
			"Node.js",
			"Express",
			"ubi8"
		]
	},
	{
		"Name": "nodejs-angular",
		"Language": "TypeScript",
		"ProjectType": "Angular",
		"Tags": [
			"Node.js",
			"Angular"
		]
	},
	{
		"Name": "nodejs-nextjs",
		"Language": "TypeScript",
		"ProjectType": "Next.js",
		"Tags": [
			"Node.js",
			"Next.js"
		]
	},
	{
		"Name": "nodejs-nuxtjs",
		"Language": "TypeScript",
		"ProjectType": "Nuxt.js",
		"Tags": [
			"Node.js",
			"Nuxt.js"
		]
	},
	{
		"Name": "nodejs-react",
		"Language": "TypeScript",
		"ProjectType": "React",
		"Tags": [
			"Node.js",
			"React"
		]
	},
	{
		"Name": "nodejs-svelte",
		"Language": "TypeScript",
		"ProjectType": "Svelte",
		"Tags": [
			"Node.js",
			"Svelte"
		]
	},
	{
		"Name": "nodejs-vue",
		"Language": "TypeScript",
		"ProjectType": "Vue",
		"Tags": [
			"Node.js",
			"Vue"
		]
	}
]
```

Alizer should be able to recognize the Lavarel component and assign the correct devfile.

**Target date**: 18 May 2023

**Comment by mike-hoang** [comment]
Explored the potential config files for the `lavarel_detector.go` and it does work. Also using the `composer.json` to identify php works as it's unique to php. Will continue to work on the `php_enricher` and detector tomorrow

**Comment by mike-hoang** [comment]
[Opened a draft PR](https://github.com/redhat-developer/alizer/pull/207), investigating failure on the external repo test. Might be this directory that is failing -- `"directory": "translate-example-func"`.

Updating target date for review process and further testing

**Comment by mike-hoang** [comment]
External repo test is fixed and [PR](https://github.com/redhat-developer/alizer/pull/207) moved to ready for review
