### ISSUE TITLE
Alizer should ignore pointer when looking for regex match for port detection

### ISSUE THREAD

**Issue by yangcao77** [redhat-developer/alizer#199]
Run alizer against https://github.com/openshift/hypershift/tree/release-4.14 to detect components
got error:

```
regexp: Compile(`*flHTTPAddr\s+[:=]+\s"([^"]*)`): error parsing regexp: missing argument to repetition operator: `*`

goroutine 1 [running]:
regexp.MustCompile({0xc00042c0a0, 0x1d})
        /usr/local/go/src/regexp/regexp.go:317 +0xbb
github.com/redhat-developer/alizer/go/pkg/apis/enricher/framework/go.GetPortWithMatchIndexesGo({0xc000d3b000, 0x4ea5}, {0xc0001ba020, 0x10c72c0?, 0xc0000d0060?}, {0x179a119?, 0xc00063f048?})
        /Users/stephanie/go/src/github.com/redhat-developer/alizer/go/pkg/apis/enricher/framework/go/go_detector.go:113 +0x130
```

it is because Alizer try to look for match of `Addr` in order to get port: https://github.com/redhat-developer/alizer/blob/baf25f6252d35c1056a556b6276eb1f7455e931f/go/pkg/apis/enricher/framework/go/mux_detector.go#L50

but in any repository, the variable can be with `Addr` as well, and also pointers contains invalid character `*`
https://github.com/openshift/hypershift/blob/e7eb32f259b2a01e5bbdddf2fe963b82b331180f/hack/tools/vendor/github.com/ahmetb/gen-crd-api-reference-docs/main.go#L90-L93

UPDATE: @thepetk 
**target date**: 8 May 2023

**Comment by elsony** [comment]
@thepetk Please work on this with priority. We'll need this as part of the Service Preview for HAS.

**Comment by thepetk** [comment]
@elsony the issue description is very helpful and I've already been investigating. I'll try to create (at least a draft) a PR with a workaround today :)

**Comment by thepetk** [comment]
UPDATE: I've created a [PR](https://github.com/redhat-developer/alizer/pull/200) for this issue.
