### ISSUE TITLE
Create utils unit tests

### ISSUE THREAD

**Issue by thepetk** [redhat-developer/alizer#206]
## Which area this feature is related to?

/area test-automation

## Issue details

In order to improve the test coverage and have a more reliable testing, we should create unit tests dedicated to [pkg/utils](https://github.com/redhat-developer/alizer/tree/main/go/pkg/utils).

**Target Date**: 01 June 2023

**Comment by mike-hoang** [comment]
Completed half the missing util tests. Updating target date for adding the rest of the test and review.

**Comment by mike-hoang** [comment]
[PR](https://github.com/redhat-developer/alizer/pull/223) is now ready for review
