### ISSUE TITLE
Alizer component scanning should exclude vendor folders

### ISSUE THREAD

**Issue by yangcao77** [redhat-developer/alizer#208]
as discussed in https://redhat-internal.slack.com/archives/C04PZ7H0VA8/p1683797822489049

the vendor folder were also scanned and components are being returned

which is causing performance problems as time was spent on unnecessary files & folders for component/port detection

**Comment by mike-hoang** [comment]
Added `vendor` to the Go `exclude_folders` in the `languages-customization.yml` and confirmed that the directory is skipped when scanning.

External repo test is failing (maybe due to how the [repo](https://github.com/devfile-resources/alizer-test-resources) is structured), will look into it
