### ISSUE TITLE
Add port detection for the Laravel detector

### ISSUE THREAD

**Issue by mike-hoang** [redhat-developer/alizer#212]
## Which area this feature is related to?

/area cli
/area library

## Issue details

After fixing https://github.com/redhat-developer/alizer/issues/188, we are able to detect Laravel framework for PHP projects. This issue is dedicated to port detection logic that should be added to the `lavarel_detector.go` 

The function which will be the entrypoint for this detection logic will be `DoPortDetection` in [laravel_detector.go](https://github.com/redhat-developer/alizer/blob/main/go/pkg/apis/enricher/framework/php/laravel_detector.go#L26)

### Potential Workaround
We might be able to get configured ports from env vars:

```
# .env file
SERVER_PORT="9000"
```

**Comment by thepetk** [comment]
**Target Date**: 28 June 2023

I've found that APP_PORT would be the workaround, but indeed I've created a [PR]( #241) in order to add a very simple port detection logic

**Comment by thepetk** [comment]
Regarding the need for `default ports` I've introduced the `EPIC` #245 in order to follow this feature there
