### ISSUE TITLE
Update and re-structure documentation

### ISSUE THREAD

**Issue by thepetk** [redhat-developer/alizer#215]
## Which area this feature is related to?

/area documentation

## Which area is this documentation change is related to?

/area library

## Issue details

After all the changes introduced in the last issues that we have completed (removal of JS and Java implementation etc), we need to update the Readme.md file and the docs/name_detection.md.

**Comment by thepetk** [comment]
Another point here should be to add also documentation to devfile.io as this service will be onboarded to devfiles team

**Comment by mike-hoang** [comment]
Also need to add build instructions

**Comment by mike-hoang** [comment]
[PR](https://github.com/redhat-developer/alizer/pull/236) opened and ready for review
