### ISSUE TITLE
Create proposal for defining a dockerfile component

### ISSUE THREAD

**Issue by mike-hoang** [redhat-developer/alizer#244]
## Which area/kind this issue is related to?

/area cli
/area library

## Issue Description

Related: EPIC https://github.com/redhat-developer/alizer/issues/235

To improve port detection around dockerfiles, we need to consider cases where a dockerfile may not be inside a detected component. This requires a new component definition which this proposal will focus on.

**Target date:** June 30

**Comment by thepetk** [comment]
Closing in favor of https://github.com/devfile/api/issues/1160
