### ISSUE TITLE
binary builds for alizer-cli

### ISSUE THREAD

**Issue by kadel** [redhat-developer/alizer#40]
It would be nice to have a pre-build binaries that can be just dowload for all major operating systems (windows, mac, linux) and architectures (amd64,ppc64le, s390x).

**Comment by lstocchi** [comment]
yeah the service reco PR is still on progress and the fix is there. Let me extract the fix and merge it.

**Comment by thepetk** [comment]
I've created a [PR](https://github.com/redhat-developer/alizer/pull/237) for this issue. I have tested the new flow in my fork here: https://github.com/thepetk/alizer/releases/tag/v1.0.0

**Comment by thepetk** [comment]
After the point raised in the review of the PR, I'm checking for additional actions we need to cover when we generate the binaries

**Comment by thepetk** [comment]
I'm still working on the points raised. I'm looking for an efficient way to sign the upload binaries

**Comment by thepetk** [comment]
As discussed we should follow the github actions workflow for binaries creation. Putting this back in review as no updates are required.

**Comment by thepetk** [comment]
I've updated the PR after the first review and now is again under review status
