### ISSUE TITLE
unable to import go implementation in another project

### ISSUE THREAD

**Issue by kadel** [redhat-developer/alizer#65]
With the new structure, I'm not able to simply import Alizer go module in my project.

There are two problems. 

First, the go module is located at `github.com/redhat-developer/alizer/go` but `go.mod` defines it as `github.com/redhat-developer/alizer`. This is not a big deal as it can be easily solved in `go.mod` of the project that needs to import this. All that this required is to specify the following "replace" and run `go mod tidy`.

```
replace(
 github.com/redhat-developer/alizer =>  github.com/redhat-developer/alizer/go main
)
```

The second problem is more tricky. It has to do with `languages.yml` and `languages-customization.yml`. They are copied by `make init` but when you are importing libraries in go they are just cloned and there is no way to execute that command.

We will have to figure out a better way to handle this. Especially the language yaml files.

**Comment by lstocchi** [comment]
Ok, I guess we have no other option. I'll create a gh action which check if the languages yaml files are in sync just to be sure
