### ISSUE TITLE
sum of UsageInPercentage is over 100%

### ISSUE THREAD

**Issue by kadel** [redhat-developer/alizer#77]
Running `recognizer.Analyzer` returns `UsageInPercentage` which sum is way over 100%

Based on the name I would assume that the UsageInPercentage should indicate how much each language is used in the directory that is being analyzed and the sum of all UsageInPercentage should be exactly 100.

```
Runing recognizer.Analyzer("spring-petclinic")
{Name:Java Aliases:[] UsageInPercentage:76.08 Frameworks:[Spring] Tools:[Maven] CanBeComponent:true}
{Name:SQLPL Aliases:[] UsageInPercentage:19.56 Frameworks:[] Tools:[] CanBeComponent:false}
{Name:TSQL Aliases:[] UsageInPercentage:19.56 Frameworks:[] Tools:[] CanBeComponent:false}
{Name:PLSQL Aliases:[] UsageInPercentage:19.56 Frameworks:[] Tools:[] CanBeComponent:false}
{Name:PLpgSQL Aliases:[] UsageInPercentage:19.56 Frameworks:[] Tools:[] CanBeComponent:false}
{Name:Batchfile Aliases:[bat batch dosbatch winbatch] UsageInPercentage:2.17 Frameworks:[] Tools:[] CanBeComponent:false}
{Name:GCC Machine Description Aliases:[] UsageInPercentage:2.17 Frameworks:[] Tools:[] CanBeComponent:false}

````

**Comment by lstocchi** [comment]
I don't know what could be a good output here. Alizer discovered some files/extensions which are associated to different "languages" (SPLPL, TSQL, PLSQL,...) and their `percentage` is replicated for each entry. So it's not actually wrong. A sql script can be TSQL or PLSQL or PLpgSQL, alizer doesn't know it... so it tells that there are x file associated to SQLPL, x file TSQL and so on ...  maybe we should handle this SQL case in a customized way. But then there could be other cases where an extension is used in multiple languages... In the case there will be some overlapping, the percentage will be over 100.
How do you see it? Ideas?

**Comment by kadel** [comment]
I did not realize that there some extensions can be associated with multiple languages. I see why it is, and it kind of makes sense. But I'm not sure if this is going to be clear to users.
Maybe it is just a matter of explaining this in the comments/documentation somewhere.

Another option could be to simply not calling it `percentage`, but just `weight` or `score` or something like this. 

It could de just my OCD looking for what is 100% every time i see percentages :-D

**Comment by lstocchi** [comment]
Yeah, changing name to `weight` or `score` makes sense. I'll do it :+1:
